sudo: required
dist: trusty
language: c

script:
  - sudo apt-get purge apparmor
  - sudo apt-get install apparmor
  - apparmor_parser --version
  - apparmor_parser --skip-cache --names --debug --Include /etc/apparmor.d/ --Include . $(find -maxdepth 1 -type f  |grep -E '^\./[[:lower:]][[:lower:]\.]+')
